// KlasUp Guide — structured content (converted from klasup-guide-draft.md v2)
// DO NOT edit prose here — all copy is verbatim from the approved draft.

export const sections = [
  {
    id: "dashboard",
    emoji: "\u{1F3E0}",
    title: "Dashboard",
    comingSoon: false,
    whatThisIs: "Your home base. The Dashboard shows you what\u2019s happening across your teaching this term \u2014 your recent activity, how your pace compares week to week, and one suggested next step based on what you\u2019ve been working on. It\u2019s designed to answer \u201Cwhat should I do next?\u201D in the first ten seconds of logging in.",
    howToUse: "Log in and scan the top: your activity cards show what you\u2019ve done this week versus last. The \u201CSuggested Next Step\u201D card offers one concrete action \u2014 take it or ignore it, it\u2019s a nudge, not a to-do list. Below that, \u201COther things you could do\u201D gives alternatives, and your recent activity keeps the thread of where you left off. Check in for two minutes at the start of a work session; everything else in KlasUp is one click away from here.",
    relatedTerms: ["whole-student-support"],
  },
  {
    id: "career-connections",
    emoji: "\u{1F4BC}",
    title: "Career Connections",
    comingSoon: false,
    whatThisIs: "Career Connections shows how each of your courses prepares students for their working lives. For every course, KlasUp generates a plain-language picture of the skills your course builds and the kinds of roles those skills apply to \u2014 grounded in what your course actually teaches, not in market statistics or job-growth claims. It\u2019s the answer to the question students ask most: \u201CWhen will I ever use this?\u201D",
    howToUse: "On your Dashboard, find your course in the class list and expand it. You\u2019ll see the career framing for that course: the transferable skills it develops and where those skills show up professionally. Use it when writing your syllabus\u2019s \u201Cwhy this course matters\u201D section, when a student asks how the material connects to their future, or when making the workforce-relevance case to your department. It generates automatically the first time you view a course and stays ready after that.",
    relatedTerms: ["learning-outcome"],
  },
  {
    id: "klas",
    emoji: "\u{1F33F}",
    title: "Klas",
    comingSoon: false,
    whatThisIs: "Klas is your personal teaching coach \u2014 an AI assistant trained on peer-reviewed pedagogy research, available on every page of KlasUp. Klas answers teaching questions, helps you think through course design, and gives feedback grounded in learning science rather than opinion. Think of Klas as the instructional designer most faculty never had access to.",
    howToUse: "Click the green bubble in the bottom-right corner of any page. Ask anything you\u2019d ask a trusted teaching mentor: \u201CHow do I get students to actually do the reading?\u201D \u201CIs this assignment too easy?\u201D \u201CMy discussion boards are dead \u2014 help.\u201D You can type or use voice input. Klas knows which page you\u2019re on, so questions like \u201Chow should I improve this?\u201D land in context. Conversations are a space to think out loud \u2014 no question is too basic.",
    relatedTerms: ["blooms-taxonomy", "scaffolding", "active-learning"],
  },
  {
    id: "course-architect",
    emoji: "\u{1F4D0}",
    title: "Course Architect",
    comingSoon: false,
    whatThisIs: "Course Architect is where you design your course as a whole \u2014 your term at a glance. It holds your learning outcomes, your week-by-week plan, and your assignments, all connected: every week and assignment can be tagged to the outcomes it serves, so you can see exactly how your course design delivers what it promises. Three views (List, Assignments, Details) show the same course from different angles.",
    howToUse: "Pick your course from the pill at the top right, then click \u201CEdit this course\u2019s setup\u201D to build: add your learning outcomes first (they\u2019re the backbone), then fill in each week\u2019s topic, then add your assignments and place them on the calendar. Tag everything to outcomes as you go. Back on the main Course Architect page, use the List view for a quick scan of the term, the Assignments view to see your assessment plan (and send any assignment to Pedagogy Studio for AI feedback with one click), and the Details view for the full week-by-week picture. Click any outcome pill at the top to filter everything to just that outcome.",
    relatedTerms: ["learning-outcome", "scaffolding", "summative-assessment"],
  },
  {
    id: "pedagogy-studio",
    emoji: "\u{1F4DA}",
    title: "Pedagogy Studio",
    comingSoon: false,
    whatThisIs: "Pedagogy Studio is where your teaching materials get research-backed feedback. Share anything \u2014 an assignment, an announcement, class notes, a discussion prompt \u2014 by typing, pasting, speaking, or uploading a file, and Klas analyzes it against the learning science and returns specific, cited recommendations you can act on immediately.",
    howToUse: "Choose what kind of material you\u2019re sharing (assignment, announcement, discussion, and so on), then add your content \u2014 type it, dictate it, or drag in a file. Click submit, and within moments you\u2019ll see recommendations: what\u2019s working, what could be stronger, and the research behind each suggestion. Your submission history lives below, organized by week, so you can watch your practice evolve across the term. Tip: in Course Architect\u2019s Assignments view, the \u201CGet AI feedback\u201D button sends any assignment here pre-filled \u2014 and the feedback flows back onto that assignment, so it\u2019s waiting where the assignment lives.",
    relatedTerms: ["blooms-taxonomy", "scaffolding", "active-learning", "formative-assessment", "rubric"],
  },
  {
    id: "slide-studio",
    emoji: "\u{1F4CA}",
    title: "Slide Studio",
    comingSoon: false,
    whatThisIs: "Slide Studio turns a plain-English description of a class session into a complete, teaching-ready slide outline \u2014 slide-by-slide structure, talking points, suggested activities, speaker notes, and time estimates. It also reviews your deck through a learning-science lens, flagging where active learning could replace straight lecture.",
    howToUse: "Describe the session in ordinary language \u2014 \u201Ca 75-minute intro to market segmentation for sophomores, with one group activity\u201D \u2014 and Slide Studio drafts the outline. Refine it the same way: \u201Cmake slide 4 more interactive,\u201D \u201Cadd a real-world example.\u201D You can also upload an existing deck for analysis. When it\u2019s ready, export to PowerPoint and make it yours.",
    relatedTerms: ["universal-design-for-learning", "active-learning", "accessibility"],
  },
  {
    id: "wellness",
    emoji: "\u{1F33F}",
    title: "Wellness",
    comingSoon: false,
    whatThisIs: "Wellness is the part of KlasUp that takes care of you \u2014 and helps you take care of the whole student. It includes a gentle daily check-in, guided audio meditations recorded for the realities of teaching (before a tough class, after a draining week), breathing exercises with selectable patterns, and short practices you can share with students for moments like test anxiety or mid-term burnout.",
    howToUse: "The check-in lives on your Dashboard \u2014 one tap, no journaling required, just an honest signal to yourself. Visit the Wellness page when you need more: the \u201CYour Wellbeing\u201D tab holds the faculty meditations and breathing exercises (pick a pattern and duration, press begin); the \u201CYour Students\u201D tab holds practices designed for student moments, plus trauma-informed teaching resources. Two minutes before class is enough.",
    relatedTerms: ["trauma-informed-teaching", "whole-student-support", "belonging"],
  },
  {
    id: "student-voice",
    emoji: "\u{1F3A4}",
    title: "Student Voice",
    comingSoon: false,
    whatThisIs: "Student Voice helps you bring students\u2019 perspectives into how your course runs. It\u2019s a collection of concrete strategies for gathering student input \u2014 exit tickets, anonymous feedback, structured check-ins \u2014 along with ready-to-use assignment templates and prompts that invite students to shape their own learning.",
    howToUse: "Open Student Voice from the sidebar and browse the strategy cards. Each one explains the approach and gives you copy-ready text to drop into your LMS or syllabus. Start small: one exit-ticket question at the end of this week\u2019s class is a complete first step. The strategies scale from five-minute additions to full assignments.",
    relatedTerms: ["belonging", "active-learning", "formative-assessment"],
  },
  {
    id: "micro-learning",
    emoji: "\u{1F4A1}",
    title: "Micro-Learning",
    comingSoon: false,
    whatThisIs: "Micro-Learning is professional development that fits inside a faculty schedule: short, research-backed teaching recommendations, each grounded in peer-reviewed literature and tied to what you\u2019re actually working on. No workshops, no webinars \u2014 two minutes of reading with a citation you can trust.",
    howToUse: "Recommendations appear throughout KlasUp \u2014 on your Dashboard and alongside your Pedagogy Studio submissions \u2014 matched to your recent work. Read the suggestion, check the research behind it, and try the technique in your next class. Rate the ones you use; it sharpens what gets recommended next.",
    relatedTerms: [],
  },
  {
    id: "research-library",
    emoji: "\u{1F52C}",
    title: "Research Library",
    comingSoon: false,
    whatThisIs: "The Research Library is KlasUp\u2019s evidence base: a curated, searchable collection of peer-reviewed articles on teaching and learning, spanning dimensions from assessment design to inclusive teaching. It\u2019s the same research that powers Klas\u2019s recommendations \u2014 open for you to explore directly. It\u2019s also publicly available at klasup.com/research, no login required.",
    howToUse: "Search by keyword, author, or title, or filter by teaching dimension to browse an area you\u2019re working on. Use it when you want to go deeper than a recommendation \u2014 to read the actual study behind a practice, or to gather sources for a teaching statement, a promotion dossier, or a curriculum committee conversation. Every glossary term below links to its supporting articles here.",
    relatedTerms: [],
  },
  {
    id: "think-tank",
    emoji: "\u{1F4AC}",
    title: "Think Tank",
    comingSoon: false,
    whatThisIs: "Think Tank is the faculty room \u2014 a forum where KlasUp faculty across institutions share what\u2019s working, ask what isn\u2019t, and think together about teaching. Conversations are organized by topic, and contributions from experienced voices carry expert badges.",
    howToUse: "Browse by topic or post your own question \u2014 the messy, real ones are the most valuable (\u201Cmy group projects keep collapsing \u2014 what do you all do?\u201D). Reply to others when you\u2019ve tried something that worked; upvote what helps you. Teaching is less isolating with colleagues in the room.",
    relatedTerms: [],
  },
  {
    id: "course-portfolio",
    emoji: "\u{1F5C4}\uFE0F",
    title: "Course Portfolio",
    comingSoon: false,
    whatThisIs: "Course Portfolio is your teaching record for the term \u2014 everything you\u2019ve built and submitted, organized by week and category, with the AI recommendations you received alongside each piece. At term\u2019s end, it helps you write a reflection on how the course went, with an AI-drafted starting point you edit into your own words.",
    howToUse: "Visit it anytime to see the term\u2019s arc \u2014 it builds itself as you work, no upkeep required. At the end of the term, open the End of Term Reflection: review the draft, make it honest and yours, and export the portfolio as PDF or Word. It\u2019s ready-made evidence for annual reviews, promotion files, and your own sense of how far the course has come.",
    relatedTerms: [],
  },
  {
    id: "reports",
    emoji: "\u{1F4CB}",
    title: "Reports",
    comingSoon: true,
    whatThisIs: "Reports will connect your everyday teaching work to accreditation evidence \u2014 mapping what you build and document in KlasUp to the standards your institution answers to (NECHE, HLC, SACSCOC, AACSB), exportable in formats committees actually use. It exists today in an early form and is being rebuilt to do this properly; the full version arrives with KlasUp\u2019s new scoring system.",
    howToUse: null,
    relatedTerms: [],
  },
  {
    id: "health-scores",
    emoji: "\u{1F4C8}",
    title: "Health Scores",
    comingSoon: true,
    whatThisIs: "Health Scores will measure something most teaching metrics ignore: growth. Instead of a single judgment number, KlasUp is building two parallel scores \u2014 a Global Growth Score (course design, inclusive teaching, assessment) and a Wellness Core (whole-student support) \u2014 that measure your trajectory, calibrated to your career stage. A new faculty member building their practice and a veteran refining theirs both get scores that mean something. Every score will come with a full \u201Cwhy\u201D \u2014 what you told us, what we analyzed \u2014 no black boxes.",
    howToUse: "In development now. When it arrives, your scores will appear on your Dashboard once your course has enough real material to score honestly \u2014 KlasUp won\u2019t show a number it can\u2019t defend.",
    relatedTerms: [],
  },
];

export const glossary = [
  {
    id: "learning-outcome",
    term: "Learning Outcome",
    definition: "A clear statement of what students will be able to do by the end of your course. Outcomes are the backbone of course design: assignments, activities, and assessments all exist to serve them.",
    livesIn: ["course-architect", "career-connections"],
  },
  {
    id: "blooms-taxonomy",
    term: "Bloom\u2019s Taxonomy",
    definition: "A framework describing levels of thinking, from remembering facts up through analyzing, evaluating, and creating. A well-designed course moves students across multiple levels, not just the lower ones.",
    livesIn: ["pedagogy-studio", "klas"],
  },
  {
    id: "scaffolding",
    term: "Scaffolding",
    definition: "Structuring work so complexity builds in steps \u2014 drafts before finals, milestones before deadlines \u2014 with support that gradually steps back as students grow capable.",
    livesIn: ["course-architect", "pedagogy-studio", "klas"],
  },
  {
    id: "universal-design-for-learning",
    term: "Universal Design for Learning (UDL)",
    definition: "Designing your course so all students can engage with it from the start: multiple ways to encounter material, multiple ways to show learning. Designed-in access, not retrofitted accommodation.",
    livesIn: ["slide-studio"],
  },
  {
    id: "accessibility",
    term: "Accessibility",
    definition: "The practical side of reaching every learner: plain language, clear structure, readable formats, materials that work for students with disabilities. Accessible design helps everyone, not only those who require it.",
    livesIn: ["slide-studio"],
  },
  {
    id: "active-learning",
    term: "Active Learning",
    definition: "Any approach where students do something with the material \u2014 discuss, apply, build, solve \u2014 rather than only listening. One of the most consistently supported findings in learning research.",
    livesIn: ["pedagogy-studio", "slide-studio", "student-voice", "klas"],
  },
  {
    id: "formative-assessment",
    term: "Formative Assessment",
    definition: "Low-stakes checks on learning while it\u2019s happening \u2014 practice quizzes, drafts, quick polls \u2014 so students and you can adjust before the stakes get high.",
    livesIn: ["pedagogy-studio", "student-voice"],
  },
  {
    id: "summative-assessment",
    term: "Summative Assessment",
    definition: "The high-stakes measurement at the end \u2014 exams, final papers, projects \u2014 evaluating what learning happened.",
    livesIn: ["course-architect"],
  },
  {
    id: "rubric",
    term: "Rubric",
    definition: "A written guide showing exactly what quality looks like on an assignment, criterion by criterion. Rubrics make expectations transparent and grading consistent.",
    livesIn: ["pedagogy-studio"],
  },
  {
    id: "belonging",
    term: "Belonging",
    definition: "A student\u2019s sense that they\u2019re seen, expected, and welcome in your course. Inclusive language, varied examples, and a humane tone are design choices that build it.",
    livesIn: ["wellness", "student-voice"],
  },
  {
    id: "trauma-informed-teaching",
    term: "Trauma-Informed Teaching",
    definition: "Designing with the awareness that many students carry difficult experiences: predictable structure, flexibility without forced disclosure, and connection to support resources.",
    livesIn: ["wellness"],
  },
  {
    id: "whole-student-support",
    term: "Whole-Student Support",
    definition: "Teaching that recognizes students as people first: connecting them to resources (counseling, tutoring, food security), building reasonable flexibility into policies, and writing course materials that treat them as humans.",
    livesIn: ["wellness", "dashboard"],
  },
];
